# Generated by Django 2.0.2 on 2018-02-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkary', '0004_auto_20180211_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'get_latest_by': ['time_created']},
        ),
    ]
