# Generated by Django 2.0.2 on 2018-02-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkary', '0006_auto_20180212_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'get_latest_by': ['time_created'], 'ordering': ['-time_modified']},
        ),
    ]
